# Regression with Discrete Dependent Variable
This is a notebook with notes about the methods of this link:
https://www.statsmodels.org/stable/discretemod.html

In [4]:
import statsmodels.api as sm

In [5]:
# Load the data from Spector and Mazzeo (1980)
spector_data = sm.datasets.spector.load_pandas()

In [7]:
spector_data.exog = sm.add_constant(spector_data.exog)

C:\Users\willi\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [8]:
# Logit Model
logit_mod = sm.Logit(spector_data.endog, spector_data.exog)

In [11]:
logit_res = logit_mod.fit()

Optimization terminated successfully.
         Current function value: 0.402801
         Iterations 7

In [12]:
print(logit_res.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Mon, 09 Sep 2019   Pseudo R-squ.:                  0.3740
Time:                        14:43:44   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -13.0213      4.931     -2.641      0.008     -22.687      -3.356
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.025       0.292       4.465
==============================================================================

In [13]:
Xall = spector_data.data.copy()

In [14]:
Xall

     GPA  TUCE  PSI  GRADE
0   2.66  20.0  0.0    0.0
1   2.89  22.0  0.0    0.0
2   3.28  24.0  0.0    0.0
3   2.92  12.0  0.0    0.0
4   4.00  21.0  0.0    1.0
5   2.86  17.0  0.0    0.0
6   2.76  17.0  0.0    0.0
7   2.87  21.0  0.0    0.0
8   3.03  25.0  0.0    0.0
9   3.92  29.0  0.0    1.0
10  2.63  20.0  0.0    0.0
11  3.32  23.0  0.0    0.0
12  3.57  23.0  0.0    0.0
13  3.26  25.0  0.0    1.0
14  3.53  26.0  0.0    0.0
15  2.74  19.0  0.0    0.0
16  2.75  25.0  0.0    0.0
17  2.83  19.0  0.0    0.0
18  3.12  23.0  1.0    0.0
19  3.16  25.0  1.0    1.0
20  2.06  22.0  1.0    0.0
21  3.62  28.0  1.0    1.0
22  2.89  14.0  1.0    0.0
23  3.51  26.0  1.0    0.0
24  3.54  24.0  1.0    1.0
25  2.83  27.0  1.0    1.0
26  3.39  17.0  1.0    1.0
27  2.67  24.0  1.0    0.0
28  3.65  21.0  1.0    1.0
29  4.00  23.0  1.0    1.0
30  3.10  21.0  1.0    0.0
31  2.39  19.0  1.0    1.0

In [27]:
X = Xall[['GPA','TUCE','PSI']]

In [28]:
X

     GPA  TUCE  PSI
0   2.66  20.0  0.0
1   2.89  22.0  0.0
2   3.28  24.0  0.0
3   2.92  12.0  0.0
4   4.00  21.0  0.0
5   2.86  17.0  0.0
6   2.76  17.0  0.0
7   2.87  21.0  0.0
8   3.03  25.0  0.0
9   3.92  29.0  0.0
10  2.63  20.0  0.0
11  3.32  23.0  0.0
12  3.57  23.0  0.0
13  3.26  25.0  0.0
14  3.53  26.0  0.0
15  2.74  19.0  0.0
16  2.75  25.0  0.0
17  2.83  19.0  0.0
18  3.12  23.0  1.0
19  3.16  25.0  1.0
20  2.06  22.0  1.0
21  3.62  28.0  1.0
22  2.89  14.0  1.0
23  3.51  26.0  1.0
24  3.54  24.0  1.0
25  2.83  27.0  1.0
26  3.39  17.0  1.0
27  2.67  24.0  1.0
28  3.65  21.0  1.0
29  4.00  23.0  1.0
30  3.10  21.0  1.0
31  2.39  19.0  1.0

In [29]:
X1 = sm.add_constant(X)

C:\Users\willi\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

In [30]:
X1.head()

   const   GPA  TUCE  PSI
0    1.0  2.66  20.0  0.0
1    1.0  2.89  22.0  0.0
2    1.0  3.28  24.0  0.0
3    1.0  2.92  12.0  0.0
4    1.0  4.00  21.0  0.0

In [31]:
y = Xall["GRADE"]

In [32]:
# Logit Model
logit_mod1 = sm.Logit(y, X1)
logit_res1 = logit_mod1.fit()

Optimization terminated successfully.
         Current function value: 0.402801
         Iterations 7

In [33]:
print(logit_res1.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Mon, 09 Sep 2019   Pseudo R-squ.:                  0.3740
Time:                        14:52:58   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -13.0213      4.931     -2.641      0.008     -22.687      -3.356
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.025       0.292       4.465
==============================================================================